# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Produce verbose output by default.
VERBOSE = 1

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.20.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.20.2/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/davide/Documents/Git/acme

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/davide/Documents/Git/acme

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.20.2/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.20.2/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.20.2/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.20.2/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.20.2/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.20.2/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.20.2/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.20.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/davide/Documents/Git/acme/CMakeFiles /Users/davide/Documents/Git/acme//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/davide/Documents/Git/acme/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named acme-test8

# Build rule for target.
acme-test8: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 acme-test8
.PHONY : acme-test8

# fast build rule for target.
acme-test8/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme-test8.dir/build.make CMakeFiles/acme-test8.dir/build
.PHONY : acme-test8/fast

#=============================================================================
# Target rules for targets named acme-test7

# Build rule for target.
acme-test7: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 acme-test7
.PHONY : acme-test7

# fast build rule for target.
acme-test7/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme-test7.dir/build.make CMakeFiles/acme-test7.dir/build
.PHONY : acme-test7/fast

#=============================================================================
# Target rules for targets named acme-test6

# Build rule for target.
acme-test6: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 acme-test6
.PHONY : acme-test6

# fast build rule for target.
acme-test6/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme-test6.dir/build.make CMakeFiles/acme-test6.dir/build
.PHONY : acme-test6/fast

#=============================================================================
# Target rules for targets named acme-test9

# Build rule for target.
acme-test9: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 acme-test9
.PHONY : acme-test9

# fast build rule for target.
acme-test9/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme-test9.dir/build.make CMakeFiles/acme-test9.dir/build
.PHONY : acme-test9/fast

#=============================================================================
# Target rules for targets named acme-test3

# Build rule for target.
acme-test3: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 acme-test3
.PHONY : acme-test3

# fast build rule for target.
acme-test3/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme-test3.dir/build.make CMakeFiles/acme-test3.dir/build
.PHONY : acme-test3/fast

#=============================================================================
# Target rules for targets named acme-test13

# Build rule for target.
acme-test13: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 acme-test13
.PHONY : acme-test13

# fast build rule for target.
acme-test13/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme-test13.dir/build.make CMakeFiles/acme-test13.dir/build
.PHONY : acme-test13/fast

#=============================================================================
# Target rules for targets named acme-test0

# Build rule for target.
acme-test0: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 acme-test0
.PHONY : acme-test0

# fast build rule for target.
acme-test0/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme-test0.dir/build.make CMakeFiles/acme-test0.dir/build
.PHONY : acme-test0/fast

#=============================================================================
# Target rules for targets named acme-test10

# Build rule for target.
acme-test10: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 acme-test10
.PHONY : acme-test10

# fast build rule for target.
acme-test10/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme-test10.dir/build.make CMakeFiles/acme-test10.dir/build
.PHONY : acme-test10/fast

#=============================================================================
# Target rules for targets named acme-test2

# Build rule for target.
acme-test2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 acme-test2
.PHONY : acme-test2

# fast build rule for target.
acme-test2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme-test2.dir/build.make CMakeFiles/acme-test2.dir/build
.PHONY : acme-test2/fast

#=============================================================================
# Target rules for targets named acme-test12

# Build rule for target.
acme-test12: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 acme-test12
.PHONY : acme-test12

# fast build rule for target.
acme-test12/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme-test12.dir/build.make CMakeFiles/acme-test12.dir/build
.PHONY : acme-test12/fast

#=============================================================================
# Target rules for targets named acme-test14

# Build rule for target.
acme-test14: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 acme-test14
.PHONY : acme-test14

# fast build rule for target.
acme-test14/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme-test14.dir/build.make CMakeFiles/acme-test14.dir/build
.PHONY : acme-test14/fast

#=============================================================================
# Target rules for targets named acme-test1

# Build rule for target.
acme-test1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 acme-test1
.PHONY : acme-test1

# fast build rule for target.
acme-test1/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme-test1.dir/build.make CMakeFiles/acme-test1.dir/build
.PHONY : acme-test1/fast

#=============================================================================
# Target rules for targets named acme_osx

# Build rule for target.
acme_osx: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 acme_osx
.PHONY : acme_osx

# fast build rule for target.
acme_osx/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx.dir/build.make CMakeFiles/acme_osx.dir/build
.PHONY : acme_osx/fast

#=============================================================================
# Target rules for targets named acme-test5

# Build rule for target.
acme-test5: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 acme-test5
.PHONY : acme-test5

# fast build rule for target.
acme-test5/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme-test5.dir/build.make CMakeFiles/acme-test5.dir/build
.PHONY : acme-test5/fast

#=============================================================================
# Target rules for targets named acme-test11

# Build rule for target.
acme-test11: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 acme-test11
.PHONY : acme-test11

# fast build rule for target.
acme-test11/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme-test11.dir/build.make CMakeFiles/acme-test11.dir/build
.PHONY : acme-test11/fast

#=============================================================================
# Target rules for targets named acme-test4

# Build rule for target.
acme-test4: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 acme-test4
.PHONY : acme-test4

# fast build rule for target.
acme-test4/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme-test4.dir/build.make CMakeFiles/acme-test4.dir/build
.PHONY : acme-test4/fast

#=============================================================================
# Target rules for targets named acme_osx_static

# Build rule for target.
acme_osx_static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 acme_osx_static
.PHONY : acme_osx_static

# fast build rule for target.
acme_osx_static/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx_static.dir/build.make CMakeFiles/acme_osx_static.dir/build
.PHONY : acme_osx_static/fast

src/acme_AABBtree.o: src/acme_AABBtree.cc.o
.PHONY : src/acme_AABBtree.o

# target to build an object file
src/acme_AABBtree.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx.dir/build.make CMakeFiles/acme_osx.dir/src/acme_AABBtree.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx_static.dir/build.make CMakeFiles/acme_osx_static.dir/src/acme_AABBtree.cc.o
.PHONY : src/acme_AABBtree.cc.o

src/acme_AABBtree.i: src/acme_AABBtree.cc.i
.PHONY : src/acme_AABBtree.i

# target to preprocess a source file
src/acme_AABBtree.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx.dir/build.make CMakeFiles/acme_osx.dir/src/acme_AABBtree.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx_static.dir/build.make CMakeFiles/acme_osx_static.dir/src/acme_AABBtree.cc.i
.PHONY : src/acme_AABBtree.cc.i

src/acme_AABBtree.s: src/acme_AABBtree.cc.s
.PHONY : src/acme_AABBtree.s

# target to generate assembly for a file
src/acme_AABBtree.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx.dir/build.make CMakeFiles/acme_osx.dir/src/acme_AABBtree.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx_static.dir/build.make CMakeFiles/acme_osx_static.dir/src/acme_AABBtree.cc.s
.PHONY : src/acme_AABBtree.cc.s

src/acme_aabb.o: src/acme_aabb.cc.o
.PHONY : src/acme_aabb.o

# target to build an object file
src/acme_aabb.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx.dir/build.make CMakeFiles/acme_osx.dir/src/acme_aabb.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx_static.dir/build.make CMakeFiles/acme_osx_static.dir/src/acme_aabb.cc.o
.PHONY : src/acme_aabb.cc.o

src/acme_aabb.i: src/acme_aabb.cc.i
.PHONY : src/acme_aabb.i

# target to preprocess a source file
src/acme_aabb.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx.dir/build.make CMakeFiles/acme_osx.dir/src/acme_aabb.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx_static.dir/build.make CMakeFiles/acme_osx_static.dir/src/acme_aabb.cc.i
.PHONY : src/acme_aabb.cc.i

src/acme_aabb.s: src/acme_aabb.cc.s
.PHONY : src/acme_aabb.s

# target to generate assembly for a file
src/acme_aabb.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx.dir/build.make CMakeFiles/acme_osx.dir/src/acme_aabb.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx_static.dir/build.make CMakeFiles/acme_osx_static.dir/src/acme_aabb.cc.s
.PHONY : src/acme_aabb.cc.s

src/acme_circle.o: src/acme_circle.cc.o
.PHONY : src/acme_circle.o

# target to build an object file
src/acme_circle.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx.dir/build.make CMakeFiles/acme_osx.dir/src/acme_circle.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx_static.dir/build.make CMakeFiles/acme_osx_static.dir/src/acme_circle.cc.o
.PHONY : src/acme_circle.cc.o

src/acme_circle.i: src/acme_circle.cc.i
.PHONY : src/acme_circle.i

# target to preprocess a source file
src/acme_circle.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx.dir/build.make CMakeFiles/acme_osx.dir/src/acme_circle.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx_static.dir/build.make CMakeFiles/acme_osx_static.dir/src/acme_circle.cc.i
.PHONY : src/acme_circle.cc.i

src/acme_circle.s: src/acme_circle.cc.s
.PHONY : src/acme_circle.s

# target to generate assembly for a file
src/acme_circle.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx.dir/build.make CMakeFiles/acme_osx.dir/src/acme_circle.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx_static.dir/build.make CMakeFiles/acme_osx_static.dir/src/acme_circle.cc.s
.PHONY : src/acme_circle.cc.s

src/acme_collinear.o: src/acme_collinear.cc.o
.PHONY : src/acme_collinear.o

# target to build an object file
src/acme_collinear.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx.dir/build.make CMakeFiles/acme_osx.dir/src/acme_collinear.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx_static.dir/build.make CMakeFiles/acme_osx_static.dir/src/acme_collinear.cc.o
.PHONY : src/acme_collinear.cc.o

src/acme_collinear.i: src/acme_collinear.cc.i
.PHONY : src/acme_collinear.i

# target to preprocess a source file
src/acme_collinear.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx.dir/build.make CMakeFiles/acme_osx.dir/src/acme_collinear.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx_static.dir/build.make CMakeFiles/acme_osx_static.dir/src/acme_collinear.cc.i
.PHONY : src/acme_collinear.cc.i

src/acme_collinear.s: src/acme_collinear.cc.s
.PHONY : src/acme_collinear.s

# target to generate assembly for a file
src/acme_collinear.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx.dir/build.make CMakeFiles/acme_osx.dir/src/acme_collinear.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx_static.dir/build.make CMakeFiles/acme_osx_static.dir/src/acme_collinear.cc.s
.PHONY : src/acme_collinear.cc.s

src/acme_coplanar.o: src/acme_coplanar.cc.o
.PHONY : src/acme_coplanar.o

# target to build an object file
src/acme_coplanar.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx.dir/build.make CMakeFiles/acme_osx.dir/src/acme_coplanar.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx_static.dir/build.make CMakeFiles/acme_osx_static.dir/src/acme_coplanar.cc.o
.PHONY : src/acme_coplanar.cc.o

src/acme_coplanar.i: src/acme_coplanar.cc.i
.PHONY : src/acme_coplanar.i

# target to preprocess a source file
src/acme_coplanar.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx.dir/build.make CMakeFiles/acme_osx.dir/src/acme_coplanar.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx_static.dir/build.make CMakeFiles/acme_osx_static.dir/src/acme_coplanar.cc.i
.PHONY : src/acme_coplanar.cc.i

src/acme_coplanar.s: src/acme_coplanar.cc.s
.PHONY : src/acme_coplanar.s

# target to generate assembly for a file
src/acme_coplanar.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx.dir/build.make CMakeFiles/acme_osx.dir/src/acme_coplanar.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx_static.dir/build.make CMakeFiles/acme_osx_static.dir/src/acme_coplanar.cc.s
.PHONY : src/acme_coplanar.cc.s

src/acme_intersection.o: src/acme_intersection.cc.o
.PHONY : src/acme_intersection.o

# target to build an object file
src/acme_intersection.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx.dir/build.make CMakeFiles/acme_osx.dir/src/acme_intersection.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx_static.dir/build.make CMakeFiles/acme_osx_static.dir/src/acme_intersection.cc.o
.PHONY : src/acme_intersection.cc.o

src/acme_intersection.i: src/acme_intersection.cc.i
.PHONY : src/acme_intersection.i

# target to preprocess a source file
src/acme_intersection.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx.dir/build.make CMakeFiles/acme_osx.dir/src/acme_intersection.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx_static.dir/build.make CMakeFiles/acme_osx_static.dir/src/acme_intersection.cc.i
.PHONY : src/acme_intersection.cc.i

src/acme_intersection.s: src/acme_intersection.cc.s
.PHONY : src/acme_intersection.s

# target to generate assembly for a file
src/acme_intersection.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx.dir/build.make CMakeFiles/acme_osx.dir/src/acme_intersection.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx_static.dir/build.make CMakeFiles/acme_osx_static.dir/src/acme_intersection.cc.s
.PHONY : src/acme_intersection.cc.s

src/acme_line.o: src/acme_line.cc.o
.PHONY : src/acme_line.o

# target to build an object file
src/acme_line.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx.dir/build.make CMakeFiles/acme_osx.dir/src/acme_line.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx_static.dir/build.make CMakeFiles/acme_osx_static.dir/src/acme_line.cc.o
.PHONY : src/acme_line.cc.o

src/acme_line.i: src/acme_line.cc.i
.PHONY : src/acme_line.i

# target to preprocess a source file
src/acme_line.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx.dir/build.make CMakeFiles/acme_osx.dir/src/acme_line.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx_static.dir/build.make CMakeFiles/acme_osx_static.dir/src/acme_line.cc.i
.PHONY : src/acme_line.cc.i

src/acme_line.s: src/acme_line.cc.s
.PHONY : src/acme_line.s

# target to generate assembly for a file
src/acme_line.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx.dir/build.make CMakeFiles/acme_osx.dir/src/acme_line.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx_static.dir/build.make CMakeFiles/acme_osx_static.dir/src/acme_line.cc.s
.PHONY : src/acme_line.cc.s

src/acme_math.o: src/acme_math.cc.o
.PHONY : src/acme_math.o

# target to build an object file
src/acme_math.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx.dir/build.make CMakeFiles/acme_osx.dir/src/acme_math.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx_static.dir/build.make CMakeFiles/acme_osx_static.dir/src/acme_math.cc.o
.PHONY : src/acme_math.cc.o

src/acme_math.i: src/acme_math.cc.i
.PHONY : src/acme_math.i

# target to preprocess a source file
src/acme_math.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx.dir/build.make CMakeFiles/acme_osx.dir/src/acme_math.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx_static.dir/build.make CMakeFiles/acme_osx_static.dir/src/acme_math.cc.i
.PHONY : src/acme_math.cc.i

src/acme_math.s: src/acme_math.cc.s
.PHONY : src/acme_math.s

# target to generate assembly for a file
src/acme_math.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx.dir/build.make CMakeFiles/acme_osx.dir/src/acme_math.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx_static.dir/build.make CMakeFiles/acme_osx_static.dir/src/acme_math.cc.s
.PHONY : src/acme_math.cc.s

src/acme_orthogonal.o: src/acme_orthogonal.cc.o
.PHONY : src/acme_orthogonal.o

# target to build an object file
src/acme_orthogonal.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx.dir/build.make CMakeFiles/acme_osx.dir/src/acme_orthogonal.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx_static.dir/build.make CMakeFiles/acme_osx_static.dir/src/acme_orthogonal.cc.o
.PHONY : src/acme_orthogonal.cc.o

src/acme_orthogonal.i: src/acme_orthogonal.cc.i
.PHONY : src/acme_orthogonal.i

# target to preprocess a source file
src/acme_orthogonal.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx.dir/build.make CMakeFiles/acme_osx.dir/src/acme_orthogonal.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx_static.dir/build.make CMakeFiles/acme_osx_static.dir/src/acme_orthogonal.cc.i
.PHONY : src/acme_orthogonal.cc.i

src/acme_orthogonal.s: src/acme_orthogonal.cc.s
.PHONY : src/acme_orthogonal.s

# target to generate assembly for a file
src/acme_orthogonal.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx.dir/build.make CMakeFiles/acme_osx.dir/src/acme_orthogonal.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx_static.dir/build.make CMakeFiles/acme_osx_static.dir/src/acme_orthogonal.cc.s
.PHONY : src/acme_orthogonal.cc.s

src/acme_parallel.o: src/acme_parallel.cc.o
.PHONY : src/acme_parallel.o

# target to build an object file
src/acme_parallel.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx.dir/build.make CMakeFiles/acme_osx.dir/src/acme_parallel.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx_static.dir/build.make CMakeFiles/acme_osx_static.dir/src/acme_parallel.cc.o
.PHONY : src/acme_parallel.cc.o

src/acme_parallel.i: src/acme_parallel.cc.i
.PHONY : src/acme_parallel.i

# target to preprocess a source file
src/acme_parallel.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx.dir/build.make CMakeFiles/acme_osx.dir/src/acme_parallel.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx_static.dir/build.make CMakeFiles/acme_osx_static.dir/src/acme_parallel.cc.i
.PHONY : src/acme_parallel.cc.i

src/acme_parallel.s: src/acme_parallel.cc.s
.PHONY : src/acme_parallel.s

# target to generate assembly for a file
src/acme_parallel.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx.dir/build.make CMakeFiles/acme_osx.dir/src/acme_parallel.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx_static.dir/build.make CMakeFiles/acme_osx_static.dir/src/acme_parallel.cc.s
.PHONY : src/acme_parallel.cc.s

src/acme_plane.o: src/acme_plane.cc.o
.PHONY : src/acme_plane.o

# target to build an object file
src/acme_plane.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx.dir/build.make CMakeFiles/acme_osx.dir/src/acme_plane.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx_static.dir/build.make CMakeFiles/acme_osx_static.dir/src/acme_plane.cc.o
.PHONY : src/acme_plane.cc.o

src/acme_plane.i: src/acme_plane.cc.i
.PHONY : src/acme_plane.i

# target to preprocess a source file
src/acme_plane.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx.dir/build.make CMakeFiles/acme_osx.dir/src/acme_plane.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx_static.dir/build.make CMakeFiles/acme_osx_static.dir/src/acme_plane.cc.i
.PHONY : src/acme_plane.cc.i

src/acme_plane.s: src/acme_plane.cc.s
.PHONY : src/acme_plane.s

# target to generate assembly for a file
src/acme_plane.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx.dir/build.make CMakeFiles/acme_osx.dir/src/acme_plane.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx_static.dir/build.make CMakeFiles/acme_osx_static.dir/src/acme_plane.cc.s
.PHONY : src/acme_plane.cc.s

src/acme_ray.o: src/acme_ray.cc.o
.PHONY : src/acme_ray.o

# target to build an object file
src/acme_ray.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx.dir/build.make CMakeFiles/acme_osx.dir/src/acme_ray.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx_static.dir/build.make CMakeFiles/acme_osx_static.dir/src/acme_ray.cc.o
.PHONY : src/acme_ray.cc.o

src/acme_ray.i: src/acme_ray.cc.i
.PHONY : src/acme_ray.i

# target to preprocess a source file
src/acme_ray.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx.dir/build.make CMakeFiles/acme_osx.dir/src/acme_ray.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx_static.dir/build.make CMakeFiles/acme_osx_static.dir/src/acme_ray.cc.i
.PHONY : src/acme_ray.cc.i

src/acme_ray.s: src/acme_ray.cc.s
.PHONY : src/acme_ray.s

# target to generate assembly for a file
src/acme_ray.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx.dir/build.make CMakeFiles/acme_osx.dir/src/acme_ray.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx_static.dir/build.make CMakeFiles/acme_osx_static.dir/src/acme_ray.cc.s
.PHONY : src/acme_ray.cc.s

src/acme_segment.o: src/acme_segment.cc.o
.PHONY : src/acme_segment.o

# target to build an object file
src/acme_segment.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx.dir/build.make CMakeFiles/acme_osx.dir/src/acme_segment.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx_static.dir/build.make CMakeFiles/acme_osx_static.dir/src/acme_segment.cc.o
.PHONY : src/acme_segment.cc.o

src/acme_segment.i: src/acme_segment.cc.i
.PHONY : src/acme_segment.i

# target to preprocess a source file
src/acme_segment.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx.dir/build.make CMakeFiles/acme_osx.dir/src/acme_segment.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx_static.dir/build.make CMakeFiles/acme_osx_static.dir/src/acme_segment.cc.i
.PHONY : src/acme_segment.cc.i

src/acme_segment.s: src/acme_segment.cc.s
.PHONY : src/acme_segment.s

# target to generate assembly for a file
src/acme_segment.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx.dir/build.make CMakeFiles/acme_osx.dir/src/acme_segment.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx_static.dir/build.make CMakeFiles/acme_osx_static.dir/src/acme_segment.cc.s
.PHONY : src/acme_segment.cc.s

src/acme_sphere.o: src/acme_sphere.cc.o
.PHONY : src/acme_sphere.o

# target to build an object file
src/acme_sphere.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx.dir/build.make CMakeFiles/acme_osx.dir/src/acme_sphere.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx_static.dir/build.make CMakeFiles/acme_osx_static.dir/src/acme_sphere.cc.o
.PHONY : src/acme_sphere.cc.o

src/acme_sphere.i: src/acme_sphere.cc.i
.PHONY : src/acme_sphere.i

# target to preprocess a source file
src/acme_sphere.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx.dir/build.make CMakeFiles/acme_osx.dir/src/acme_sphere.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx_static.dir/build.make CMakeFiles/acme_osx_static.dir/src/acme_sphere.cc.i
.PHONY : src/acme_sphere.cc.i

src/acme_sphere.s: src/acme_sphere.cc.s
.PHONY : src/acme_sphere.s

# target to generate assembly for a file
src/acme_sphere.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx.dir/build.make CMakeFiles/acme_osx.dir/src/acme_sphere.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx_static.dir/build.make CMakeFiles/acme_osx_static.dir/src/acme_sphere.cc.s
.PHONY : src/acme_sphere.cc.s

src/acme_triangle.o: src/acme_triangle.cc.o
.PHONY : src/acme_triangle.o

# target to build an object file
src/acme_triangle.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx.dir/build.make CMakeFiles/acme_osx.dir/src/acme_triangle.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx_static.dir/build.make CMakeFiles/acme_osx_static.dir/src/acme_triangle.cc.o
.PHONY : src/acme_triangle.cc.o

src/acme_triangle.i: src/acme_triangle.cc.i
.PHONY : src/acme_triangle.i

# target to preprocess a source file
src/acme_triangle.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx.dir/build.make CMakeFiles/acme_osx.dir/src/acme_triangle.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx_static.dir/build.make CMakeFiles/acme_osx_static.dir/src/acme_triangle.cc.i
.PHONY : src/acme_triangle.cc.i

src/acme_triangle.s: src/acme_triangle.cc.s
.PHONY : src/acme_triangle.s

# target to generate assembly for a file
src/acme_triangle.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx.dir/build.make CMakeFiles/acme_osx.dir/src/acme_triangle.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx_static.dir/build.make CMakeFiles/acme_osx_static.dir/src/acme_triangle.cc.s
.PHONY : src/acme_triangle.cc.s

src/acme_utils.o: src/acme_utils.cc.o
.PHONY : src/acme_utils.o

# target to build an object file
src/acme_utils.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx.dir/build.make CMakeFiles/acme_osx.dir/src/acme_utils.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx_static.dir/build.make CMakeFiles/acme_osx_static.dir/src/acme_utils.cc.o
.PHONY : src/acme_utils.cc.o

src/acme_utils.i: src/acme_utils.cc.i
.PHONY : src/acme_utils.i

# target to preprocess a source file
src/acme_utils.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx.dir/build.make CMakeFiles/acme_osx.dir/src/acme_utils.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx_static.dir/build.make CMakeFiles/acme_osx_static.dir/src/acme_utils.cc.i
.PHONY : src/acme_utils.cc.i

src/acme_utils.s: src/acme_utils.cc.s
.PHONY : src/acme_utils.s

# target to generate assembly for a file
src/acme_utils.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx.dir/build.make CMakeFiles/acme_osx.dir/src/acme_utils.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme_osx_static.dir/build.make CMakeFiles/acme_osx_static.dir/src/acme_utils.cc.s
.PHONY : src/acme_utils.cc.s

tests/acme-test0.o: tests/acme-test0.cc.o
.PHONY : tests/acme-test0.o

# target to build an object file
tests/acme-test0.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme-test0.dir/build.make CMakeFiles/acme-test0.dir/tests/acme-test0.cc.o
.PHONY : tests/acme-test0.cc.o

tests/acme-test0.i: tests/acme-test0.cc.i
.PHONY : tests/acme-test0.i

# target to preprocess a source file
tests/acme-test0.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme-test0.dir/build.make CMakeFiles/acme-test0.dir/tests/acme-test0.cc.i
.PHONY : tests/acme-test0.cc.i

tests/acme-test0.s: tests/acme-test0.cc.s
.PHONY : tests/acme-test0.s

# target to generate assembly for a file
tests/acme-test0.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme-test0.dir/build.make CMakeFiles/acme-test0.dir/tests/acme-test0.cc.s
.PHONY : tests/acme-test0.cc.s

tests/acme-test1.o: tests/acme-test1.cc.o
.PHONY : tests/acme-test1.o

# target to build an object file
tests/acme-test1.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme-test1.dir/build.make CMakeFiles/acme-test1.dir/tests/acme-test1.cc.o
.PHONY : tests/acme-test1.cc.o

tests/acme-test1.i: tests/acme-test1.cc.i
.PHONY : tests/acme-test1.i

# target to preprocess a source file
tests/acme-test1.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme-test1.dir/build.make CMakeFiles/acme-test1.dir/tests/acme-test1.cc.i
.PHONY : tests/acme-test1.cc.i

tests/acme-test1.s: tests/acme-test1.cc.s
.PHONY : tests/acme-test1.s

# target to generate assembly for a file
tests/acme-test1.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme-test1.dir/build.make CMakeFiles/acme-test1.dir/tests/acme-test1.cc.s
.PHONY : tests/acme-test1.cc.s

tests/acme-test10.o: tests/acme-test10.cc.o
.PHONY : tests/acme-test10.o

# target to build an object file
tests/acme-test10.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme-test10.dir/build.make CMakeFiles/acme-test10.dir/tests/acme-test10.cc.o
.PHONY : tests/acme-test10.cc.o

tests/acme-test10.i: tests/acme-test10.cc.i
.PHONY : tests/acme-test10.i

# target to preprocess a source file
tests/acme-test10.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme-test10.dir/build.make CMakeFiles/acme-test10.dir/tests/acme-test10.cc.i
.PHONY : tests/acme-test10.cc.i

tests/acme-test10.s: tests/acme-test10.cc.s
.PHONY : tests/acme-test10.s

# target to generate assembly for a file
tests/acme-test10.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme-test10.dir/build.make CMakeFiles/acme-test10.dir/tests/acme-test10.cc.s
.PHONY : tests/acme-test10.cc.s

tests/acme-test11.o: tests/acme-test11.cc.o
.PHONY : tests/acme-test11.o

# target to build an object file
tests/acme-test11.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme-test11.dir/build.make CMakeFiles/acme-test11.dir/tests/acme-test11.cc.o
.PHONY : tests/acme-test11.cc.o

tests/acme-test11.i: tests/acme-test11.cc.i
.PHONY : tests/acme-test11.i

# target to preprocess a source file
tests/acme-test11.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme-test11.dir/build.make CMakeFiles/acme-test11.dir/tests/acme-test11.cc.i
.PHONY : tests/acme-test11.cc.i

tests/acme-test11.s: tests/acme-test11.cc.s
.PHONY : tests/acme-test11.s

# target to generate assembly for a file
tests/acme-test11.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme-test11.dir/build.make CMakeFiles/acme-test11.dir/tests/acme-test11.cc.s
.PHONY : tests/acme-test11.cc.s

tests/acme-test12.o: tests/acme-test12.cc.o
.PHONY : tests/acme-test12.o

# target to build an object file
tests/acme-test12.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme-test12.dir/build.make CMakeFiles/acme-test12.dir/tests/acme-test12.cc.o
.PHONY : tests/acme-test12.cc.o

tests/acme-test12.i: tests/acme-test12.cc.i
.PHONY : tests/acme-test12.i

# target to preprocess a source file
tests/acme-test12.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme-test12.dir/build.make CMakeFiles/acme-test12.dir/tests/acme-test12.cc.i
.PHONY : tests/acme-test12.cc.i

tests/acme-test12.s: tests/acme-test12.cc.s
.PHONY : tests/acme-test12.s

# target to generate assembly for a file
tests/acme-test12.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme-test12.dir/build.make CMakeFiles/acme-test12.dir/tests/acme-test12.cc.s
.PHONY : tests/acme-test12.cc.s

tests/acme-test13.o: tests/acme-test13.cc.o
.PHONY : tests/acme-test13.o

# target to build an object file
tests/acme-test13.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme-test13.dir/build.make CMakeFiles/acme-test13.dir/tests/acme-test13.cc.o
.PHONY : tests/acme-test13.cc.o

tests/acme-test13.i: tests/acme-test13.cc.i
.PHONY : tests/acme-test13.i

# target to preprocess a source file
tests/acme-test13.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme-test13.dir/build.make CMakeFiles/acme-test13.dir/tests/acme-test13.cc.i
.PHONY : tests/acme-test13.cc.i

tests/acme-test13.s: tests/acme-test13.cc.s
.PHONY : tests/acme-test13.s

# target to generate assembly for a file
tests/acme-test13.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme-test13.dir/build.make CMakeFiles/acme-test13.dir/tests/acme-test13.cc.s
.PHONY : tests/acme-test13.cc.s

tests/acme-test14.o: tests/acme-test14.cc.o
.PHONY : tests/acme-test14.o

# target to build an object file
tests/acme-test14.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme-test14.dir/build.make CMakeFiles/acme-test14.dir/tests/acme-test14.cc.o
.PHONY : tests/acme-test14.cc.o

tests/acme-test14.i: tests/acme-test14.cc.i
.PHONY : tests/acme-test14.i

# target to preprocess a source file
tests/acme-test14.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme-test14.dir/build.make CMakeFiles/acme-test14.dir/tests/acme-test14.cc.i
.PHONY : tests/acme-test14.cc.i

tests/acme-test14.s: tests/acme-test14.cc.s
.PHONY : tests/acme-test14.s

# target to generate assembly for a file
tests/acme-test14.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme-test14.dir/build.make CMakeFiles/acme-test14.dir/tests/acme-test14.cc.s
.PHONY : tests/acme-test14.cc.s

tests/acme-test2.o: tests/acme-test2.cc.o
.PHONY : tests/acme-test2.o

# target to build an object file
tests/acme-test2.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme-test2.dir/build.make CMakeFiles/acme-test2.dir/tests/acme-test2.cc.o
.PHONY : tests/acme-test2.cc.o

tests/acme-test2.i: tests/acme-test2.cc.i
.PHONY : tests/acme-test2.i

# target to preprocess a source file
tests/acme-test2.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme-test2.dir/build.make CMakeFiles/acme-test2.dir/tests/acme-test2.cc.i
.PHONY : tests/acme-test2.cc.i

tests/acme-test2.s: tests/acme-test2.cc.s
.PHONY : tests/acme-test2.s

# target to generate assembly for a file
tests/acme-test2.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme-test2.dir/build.make CMakeFiles/acme-test2.dir/tests/acme-test2.cc.s
.PHONY : tests/acme-test2.cc.s

tests/acme-test3.o: tests/acme-test3.cc.o
.PHONY : tests/acme-test3.o

# target to build an object file
tests/acme-test3.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme-test3.dir/build.make CMakeFiles/acme-test3.dir/tests/acme-test3.cc.o
.PHONY : tests/acme-test3.cc.o

tests/acme-test3.i: tests/acme-test3.cc.i
.PHONY : tests/acme-test3.i

# target to preprocess a source file
tests/acme-test3.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme-test3.dir/build.make CMakeFiles/acme-test3.dir/tests/acme-test3.cc.i
.PHONY : tests/acme-test3.cc.i

tests/acme-test3.s: tests/acme-test3.cc.s
.PHONY : tests/acme-test3.s

# target to generate assembly for a file
tests/acme-test3.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme-test3.dir/build.make CMakeFiles/acme-test3.dir/tests/acme-test3.cc.s
.PHONY : tests/acme-test3.cc.s

tests/acme-test4.o: tests/acme-test4.cc.o
.PHONY : tests/acme-test4.o

# target to build an object file
tests/acme-test4.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme-test4.dir/build.make CMakeFiles/acme-test4.dir/tests/acme-test4.cc.o
.PHONY : tests/acme-test4.cc.o

tests/acme-test4.i: tests/acme-test4.cc.i
.PHONY : tests/acme-test4.i

# target to preprocess a source file
tests/acme-test4.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme-test4.dir/build.make CMakeFiles/acme-test4.dir/tests/acme-test4.cc.i
.PHONY : tests/acme-test4.cc.i

tests/acme-test4.s: tests/acme-test4.cc.s
.PHONY : tests/acme-test4.s

# target to generate assembly for a file
tests/acme-test4.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme-test4.dir/build.make CMakeFiles/acme-test4.dir/tests/acme-test4.cc.s
.PHONY : tests/acme-test4.cc.s

tests/acme-test5.o: tests/acme-test5.cc.o
.PHONY : tests/acme-test5.o

# target to build an object file
tests/acme-test5.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme-test5.dir/build.make CMakeFiles/acme-test5.dir/tests/acme-test5.cc.o
.PHONY : tests/acme-test5.cc.o

tests/acme-test5.i: tests/acme-test5.cc.i
.PHONY : tests/acme-test5.i

# target to preprocess a source file
tests/acme-test5.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme-test5.dir/build.make CMakeFiles/acme-test5.dir/tests/acme-test5.cc.i
.PHONY : tests/acme-test5.cc.i

tests/acme-test5.s: tests/acme-test5.cc.s
.PHONY : tests/acme-test5.s

# target to generate assembly for a file
tests/acme-test5.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme-test5.dir/build.make CMakeFiles/acme-test5.dir/tests/acme-test5.cc.s
.PHONY : tests/acme-test5.cc.s

tests/acme-test6.o: tests/acme-test6.cc.o
.PHONY : tests/acme-test6.o

# target to build an object file
tests/acme-test6.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme-test6.dir/build.make CMakeFiles/acme-test6.dir/tests/acme-test6.cc.o
.PHONY : tests/acme-test6.cc.o

tests/acme-test6.i: tests/acme-test6.cc.i
.PHONY : tests/acme-test6.i

# target to preprocess a source file
tests/acme-test6.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme-test6.dir/build.make CMakeFiles/acme-test6.dir/tests/acme-test6.cc.i
.PHONY : tests/acme-test6.cc.i

tests/acme-test6.s: tests/acme-test6.cc.s
.PHONY : tests/acme-test6.s

# target to generate assembly for a file
tests/acme-test6.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme-test6.dir/build.make CMakeFiles/acme-test6.dir/tests/acme-test6.cc.s
.PHONY : tests/acme-test6.cc.s

tests/acme-test7.o: tests/acme-test7.cc.o
.PHONY : tests/acme-test7.o

# target to build an object file
tests/acme-test7.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme-test7.dir/build.make CMakeFiles/acme-test7.dir/tests/acme-test7.cc.o
.PHONY : tests/acme-test7.cc.o

tests/acme-test7.i: tests/acme-test7.cc.i
.PHONY : tests/acme-test7.i

# target to preprocess a source file
tests/acme-test7.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme-test7.dir/build.make CMakeFiles/acme-test7.dir/tests/acme-test7.cc.i
.PHONY : tests/acme-test7.cc.i

tests/acme-test7.s: tests/acme-test7.cc.s
.PHONY : tests/acme-test7.s

# target to generate assembly for a file
tests/acme-test7.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme-test7.dir/build.make CMakeFiles/acme-test7.dir/tests/acme-test7.cc.s
.PHONY : tests/acme-test7.cc.s

tests/acme-test8.o: tests/acme-test8.cc.o
.PHONY : tests/acme-test8.o

# target to build an object file
tests/acme-test8.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme-test8.dir/build.make CMakeFiles/acme-test8.dir/tests/acme-test8.cc.o
.PHONY : tests/acme-test8.cc.o

tests/acme-test8.i: tests/acme-test8.cc.i
.PHONY : tests/acme-test8.i

# target to preprocess a source file
tests/acme-test8.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme-test8.dir/build.make CMakeFiles/acme-test8.dir/tests/acme-test8.cc.i
.PHONY : tests/acme-test8.cc.i

tests/acme-test8.s: tests/acme-test8.cc.s
.PHONY : tests/acme-test8.s

# target to generate assembly for a file
tests/acme-test8.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme-test8.dir/build.make CMakeFiles/acme-test8.dir/tests/acme-test8.cc.s
.PHONY : tests/acme-test8.cc.s

tests/acme-test9.o: tests/acme-test9.cc.o
.PHONY : tests/acme-test9.o

# target to build an object file
tests/acme-test9.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme-test9.dir/build.make CMakeFiles/acme-test9.dir/tests/acme-test9.cc.o
.PHONY : tests/acme-test9.cc.o

tests/acme-test9.i: tests/acme-test9.cc.i
.PHONY : tests/acme-test9.i

# target to preprocess a source file
tests/acme-test9.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme-test9.dir/build.make CMakeFiles/acme-test9.dir/tests/acme-test9.cc.i
.PHONY : tests/acme-test9.cc.i

tests/acme-test9.s: tests/acme-test9.cc.s
.PHONY : tests/acme-test9.s

# target to generate assembly for a file
tests/acme-test9.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acme-test9.dir/build.make CMakeFiles/acme-test9.dir/tests/acme-test9.cc.s
.PHONY : tests/acme-test9.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... acme-test0"
	@echo "... acme-test1"
	@echo "... acme-test10"
	@echo "... acme-test11"
	@echo "... acme-test12"
	@echo "... acme-test13"
	@echo "... acme-test14"
	@echo "... acme-test2"
	@echo "... acme-test3"
	@echo "... acme-test4"
	@echo "... acme-test5"
	@echo "... acme-test6"
	@echo "... acme-test7"
	@echo "... acme-test8"
	@echo "... acme-test9"
	@echo "... acme_osx"
	@echo "... acme_osx_static"
	@echo "... src/acme_AABBtree.o"
	@echo "... src/acme_AABBtree.i"
	@echo "... src/acme_AABBtree.s"
	@echo "... src/acme_aabb.o"
	@echo "... src/acme_aabb.i"
	@echo "... src/acme_aabb.s"
	@echo "... src/acme_circle.o"
	@echo "... src/acme_circle.i"
	@echo "... src/acme_circle.s"
	@echo "... src/acme_collinear.o"
	@echo "... src/acme_collinear.i"
	@echo "... src/acme_collinear.s"
	@echo "... src/acme_coplanar.o"
	@echo "... src/acme_coplanar.i"
	@echo "... src/acme_coplanar.s"
	@echo "... src/acme_intersection.o"
	@echo "... src/acme_intersection.i"
	@echo "... src/acme_intersection.s"
	@echo "... src/acme_line.o"
	@echo "... src/acme_line.i"
	@echo "... src/acme_line.s"
	@echo "... src/acme_math.o"
	@echo "... src/acme_math.i"
	@echo "... src/acme_math.s"
	@echo "... src/acme_orthogonal.o"
	@echo "... src/acme_orthogonal.i"
	@echo "... src/acme_orthogonal.s"
	@echo "... src/acme_parallel.o"
	@echo "... src/acme_parallel.i"
	@echo "... src/acme_parallel.s"
	@echo "... src/acme_plane.o"
	@echo "... src/acme_plane.i"
	@echo "... src/acme_plane.s"
	@echo "... src/acme_ray.o"
	@echo "... src/acme_ray.i"
	@echo "... src/acme_ray.s"
	@echo "... src/acme_segment.o"
	@echo "... src/acme_segment.i"
	@echo "... src/acme_segment.s"
	@echo "... src/acme_sphere.o"
	@echo "... src/acme_sphere.i"
	@echo "... src/acme_sphere.s"
	@echo "... src/acme_triangle.o"
	@echo "... src/acme_triangle.i"
	@echo "... src/acme_triangle.s"
	@echo "... src/acme_utils.o"
	@echo "... src/acme_utils.i"
	@echo "... src/acme_utils.s"
	@echo "... tests/acme-test0.o"
	@echo "... tests/acme-test0.i"
	@echo "... tests/acme-test0.s"
	@echo "... tests/acme-test1.o"
	@echo "... tests/acme-test1.i"
	@echo "... tests/acme-test1.s"
	@echo "... tests/acme-test10.o"
	@echo "... tests/acme-test10.i"
	@echo "... tests/acme-test10.s"
	@echo "... tests/acme-test11.o"
	@echo "... tests/acme-test11.i"
	@echo "... tests/acme-test11.s"
	@echo "... tests/acme-test12.o"
	@echo "... tests/acme-test12.i"
	@echo "... tests/acme-test12.s"
	@echo "... tests/acme-test13.o"
	@echo "... tests/acme-test13.i"
	@echo "... tests/acme-test13.s"
	@echo "... tests/acme-test14.o"
	@echo "... tests/acme-test14.i"
	@echo "... tests/acme-test14.s"
	@echo "... tests/acme-test2.o"
	@echo "... tests/acme-test2.i"
	@echo "... tests/acme-test2.s"
	@echo "... tests/acme-test3.o"
	@echo "... tests/acme-test3.i"
	@echo "... tests/acme-test3.s"
	@echo "... tests/acme-test4.o"
	@echo "... tests/acme-test4.i"
	@echo "... tests/acme-test4.s"
	@echo "... tests/acme-test5.o"
	@echo "... tests/acme-test5.i"
	@echo "... tests/acme-test5.s"
	@echo "... tests/acme-test6.o"
	@echo "... tests/acme-test6.i"
	@echo "... tests/acme-test6.s"
	@echo "... tests/acme-test7.o"
	@echo "... tests/acme-test7.i"
	@echo "... tests/acme-test7.s"
	@echo "... tests/acme-test8.o"
	@echo "... tests/acme-test8.i"
	@echo "... tests/acme-test8.s"
	@echo "... tests/acme-test9.o"
	@echo "... tests/acme-test9.i"
	@echo "... tests/acme-test9.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

