acme::collection
entity::vecptr acme::collection::m_entities
Vector of shared pointers to entity objects.
Referenced by areBall, areClampable, areDegenerated, areDisk, areLine, areNonClampable, areNone, arePlane, arePoint, areRay, areSegment, areTriangle, clamp, clear, collection, containBall, containClampable, containDegenerated, containDisk, containLine, containNonClampable, containNone, containPlane, containPoint, containRay, containSegment, containTriangle, countBall, countClampable, countDegenerated, countDisk, countLine, countNonClampable, countNone, countPlane, countPoint, countRay, countSegment, countTriangle, intersection, isBall, isClampable, isDegenerated, isDisk, isLine, isNonClampable, isNone, isPlane, isPoint, isRay, isSegment, isTriangle, operator[], push_back, removeBall, removeClampable, removeDegenerated, removeDisk, removeLine, removeNonClampable, removeNone, removePlane, removePoint, removeRay, removeSegment, removeTriangle, resize, rotate, size, transform, translate.
AABBtree::ptr acme::collection::m_AABBtree
Collection AABB tree pointer.
Referenced by buildAABBtree, intersection, ptrAABBtree.
acme::collection::~collection()
Collection class destructor.
acme::collection::collection(collection const &)=default
Collection copy constructor.
acme::collection::collection(collection &&)=default
Collection move constructor.
acme::collection::collection()
Collection class constructor.
acme::collection::collection(entity::vecptr &entities)
Vector of shared pointers to entity objects
void acme::collection::clear(void)
Clear all collection object data.
Referenced by intersection.
void acme::collection::resize(size_t size)
Input size
void acme::collection::push_back(entity::ptr entity)
Input shared pointer to entity
Referenced by intersection.
entity::ptr & acme::collection::operator[](size_t i)
Input i-th value
entity::ptr const & acme::collection::operator[](size_t i) const
Input i-th value
void acme::collection::translate(vec3 const &input)
Input translation vector
void acme::collection::rotate(real angle, vec3 const &axis)
Input angle [rad]
void acme::collection::rotate(real angle, std::string const &axis)
Input angle [rad]
void acme::collection::transform(affine const &matrix)
4x4 affine transformation matrix
bool acme::collection::containNone(void) const
Check whether in the collection there are any none entity objects.
bool acme::collection::areNone(void) const
Check whether the collection is composed only by none entity objects.
bool acme::collection::isNone(size_t i) const
Input i-th value
Referenced by areNone, containNone, countNone.
void acme::collection::removeNone(void)
Remove all none entity objects from collection.
integer acme::collection::countNone(void) const
Count all none entity objects in collection.
Referenced by count.
bool acme::collection::containPoint(void) const
Check whether in the collection there are any point entity objects.
bool acme::collection::arePoint(void) const
Check whether the collection is composed only by point entity objects.
bool acme::collection::isPoint(size_t i) const
Input i-th value
Referenced by arePoint, containPoint, countPoint.
void acme::collection::removePoint(void)
Remove all point entity objects from collection.
integer acme::collection::countPoint(void) const
Count all point entity objects in collection.
Referenced by count.
bool acme::collection::containLine(void) const
Check whether in the collection there are any line entity objects.
bool acme::collection::areLine(void) const
Check whether the collection is composed only by line entity objects.
bool acme::collection::isLine(size_t i) const
Input i-th value
Referenced by areLine, containLine, countLine.
void acme::collection::removeLine(void)
Remove all line entity objects from collection.
integer acme::collection::countLine(void) const
Count all line entity objects in collection.
Referenced by count.
bool acme::collection::containRay(void) const
Check whether in the collection there are any ray entity objects.
bool acme::collection::areRay(void) const
Check whether the collection is composed only by ray entity objects.
bool acme::collection::isRay(size_t i) const
Input i-th value
Referenced by areRay, containRay, countRay.
void acme::collection::removeRay(void)
Remove all ray entity objects from collection.
integer acme::collection::countRay(void) const
Count all ray entity objects in collection.
Referenced by count.
bool acme::collection::containPlane(void) const
Check whether in the collection there are any plane entity objects.
bool acme::collection::arePlane(void) const
Check whether the collection is composed only by plane entity objects.
bool acme::collection::isPlane(size_t i) const
Input i-th value
Referenced by arePlane, containPlane, countPlane.
void acme::collection::removePlane(void)
Remove all plane entity objects from collection.
integer acme::collection::countPlane(void) const
Count all plane entity objects in collection.
Referenced by count.
bool acme::collection::containSegment(void) const
Check whether in the collection there are any segment entity objects.
bool acme::collection::areSegment(void) const
Check whether the collection is composed only by segment entity objects.
bool acme::collection::isSegment(size_t i) const
Input i-th value
Referenced by containSegment, countSegment.
void acme::collection::removeSegment(void)
Remove all segment entity objects from collection.
integer acme::collection::countSegment(void) const
Count all segment entity objects in collection.
Referenced by count.
bool acme::collection::containTriangle(void) const
Check whether in the collection there are any triangle entity objects.
bool acme::collection::areTriangle(void) const
Check whether the collection is composed only by triangle entity objects.
bool acme::collection::isTriangle(size_t i) const
Input i-th value
Referenced by areTriangle, containTriangle, countTriangle.
void acme::collection::removeTriangle(void)
Remove all triangle entity objects from collection.
integer acme::collection::countTriangle(void) const
Count all triangle entity objects in collection.
Referenced by count.
bool acme::collection::containDisk(void) const
Check whether in the collection there are any disk entity objects.
bool acme::collection::areDisk(void) const
Check whether the collection is composed only by disk entity objects.
bool acme::collection::isDisk(size_t i) const
Input i-th value
Referenced by areDisk, containDisk, countDisk.
void acme::collection::removeDisk(void)
Remove all disk entity objects from collection.
integer acme::collection::countDisk(void) const
Count all disk entity objects in collection.
Referenced by count.
bool acme::collection::containBall(void) const
Check whether in the collection there are any ball entity objects.
bool acme::collection::areBall(void) const
Check whether the collection is composed only by ball entity objects.
bool acme::collection::isBall(size_t i) const
Input i-th value
Referenced by areBall, areSegment, containBall, countBall.
void acme::collection::removeBall(void)
Remove all ball entity objects from collection.
integer acme::collection::countBall(void) const
Count all ball entity objects in collection.
Referenced by count.
bool acme::collection::containDegenerated(real tolerance=EPSILON) const
Tolerance
bool acme::collection::areDegenerated(real tolerance=EPSILON) const
Tolerance
bool acme::collection::isDegenerated(size_t i, real tolerance=EPSILON) const
Input i-th value
Referenced by areDegenerated, containDegenerated, countDegenerated.
void acme::collection::removeDegenerated(real tolerance=EPSILON)
Tolerance
integer acme::collection::countDegenerated(real tolerance=EPSILON) const
Tolerance
Referenced by count.
bool acme::collection::containClampable(void) const
Check whether in the collection there are any clampable entity objects.
bool acme::collection::areClampable(void) const
Check whether the collection is composed only by clampable entity objects.
bool acme::collection::isClampable(size_t i) const
Input i-th value
Referenced by areClampable, containClampable, countClampable.
void acme::collection::removeClampable(void)
Remove all clampable entity objects from collection.
integer acme::collection::countClampable(void) const
Count all clampable entity objects in collection.
Referenced by count.
bool acme::collection::containNonClampable(void) const
Check whether in the collection there are any non clampable entity objects.
bool acme::collection::areNonClampable(void) const
Check whether the collection is composed only by non clampable entity objects.
bool acme::collection::isNonClampable(size_t i) const
Input i-th value
Referenced by areNonClampable, containNonClampable, countNonClampable.
void acme::collection::removeNonClampable(void)
Remove all non clampable entity objects from collection.
integer acme::collection::countNonClampable(void) const
Count all non clampable entity objects in collection.
Referenced by count.
integer acme::collection::size(void) const
Get collection size (number of entities)
Referenced by intersection.
std::map< std::string, integer > acme::collection::count(real tolerance=EPSILON) const
Tolerance
Referenced by countBall, countClampable, countDegenerated, countDisk, countLine, countNonClampable, countNone, countPlane, countPoint, countRay, countSegment, countTriangle.
void acme::collection::clamp(aabb::vecptr &boxes) const
Vector of shered pointer to collection objects aabbs
Referenced by buildAABBtree.
void acme::collection::buildAABBtree(void)
Build collection AABB tree.
AABBtree::ptr const & acme::collection::ptrAABBtree(void)
Return collection AABB tree shared pointer.
Referenced by intersection.
bool acme::collection::intersection(collection &entities, collection &candidates) const
External entities collection
Referenced by intersection.
bool acme::collection::intersection(AABBtree::ptr const &AABBtree, collection &entities) const
External AABBtree object pointer
bool acme::collection::intersection(aabb::vecptr const &boxes, collection &entities) const
External aabb object pointer vector
bool acme::collection::intersection(aabb::ptr const box, collection &entities) const
External aabb object pointer
void acme::collection::intersection(collection &entities, real tolerance=EPSILON) const
Intersection candidates