acme
typedef double acme::real
Real number type.
typedef int acme::integer
Integer number type.
typedef std::ostream acme::out_stream
Output stream type.
typedef Eigen::Matrix<real, 2, 1> acme::vec2
2x1 vector type (column vector)
typedef Eigen::Matrix<real, 2, 2> acme::mat2
2x2 matrix type
typedef Eigen::Matrix<real, 3, 1> acme::vec3
3x1 vector type (column vector)
typedef Eigen::Matrix<real, 3, 3> acme::mat3
3x3 matrix type
typedef Eigen::Matrix<real, 4, 1> acme::vec4
4x1 vector type (column vector)
typedef Eigen::Matrix<real, 4, 4> acme::mat4
4x4 matrix type
typedef Eigen::Matrix<real, Eigen::Dynamic, 1> acme::vecN
Nx1 vector of real number type (column vector)
typedef Eigen::Matrix<real, Eigen::Dynamic, Eigen::Dynamic> acme::matN
NxN matrix of real number type.
typedef Eigen::DiagonalMatrix<real, 3> acme::scale
3D scaling transformation type
typedef Eigen::Translation<real, 3> acme::translate
3D translation transformation type
typedef Eigen::AngleAxis<real> acme::angleaxis
3D rotation transformation type
typedef Eigen::Transform<real, 3, Eigen::Affine> acme::affine
3D affine transformation type
real const acme::EPSILON_MACHINE
Machine epsilon epsilon static constant value.
real const acme::EPSILON_HIGH
High precision epsilon static constant value.
real const acme::EPSILON_MEDIUM
Medium precision epsilon static constant value.
real const acme::EPSILON_LOW
Low precision epsilon static constant value.
real const acme::EPSILON
Standard precision epsilon static constant value.
real const acme::INFTY
Infinity static constant value.
Referenced by acme::AABBtree::selectMinimumDistance.
real const acme::QUIET_NAN
Not-a-Number static constant value.
real const acme::PI
Pi static constant value.
Referenced by acme::ball::area, acme::disk::area, acme::disk::perimeter, acme::ball::volume.
real const acme::PIDIV180
Pi/180 static constant value.
vec2 const acme::UNITX_VEC2
X axis unit vec2 static constant object.
vec2 const acme::UNITY_VEC2
Y axis unit vec2 static constant object.
vec2 const acme::NAN_VEC2
Not-a-Number vec2 static constant object.
mat2 const acme::NAN_MAT2
Not-a-Number mat2 static constant object.
vec2 const acme::ZEROS_VEC2
Zeros vec2 static constant object.
mat2 const acme::ZEROS_MAT2
Zeros mat2 static constant object.
vec2 const acme::ONES_VEC2
Ones vec2 static constant object.
mat2 const acme::ONES_MAT2
Ones mat2 static constant object.
mat2 const acme::IDENTITY_MAT2
Identity mat2 static constant object.
vec3 const acme::UNITX_VEC3
X axis unit vec3 type.
vec3 const acme::UNITY_VEC3
Y axis unit vec3 type.
vec3 const acme::UNITZ_VEC3
Z axis unit vec3 type.
vec3 const acme::NAN_VEC3
Not-a-Number vec3 type.
mat3 const acme::NAN_MAT3
Not-a-Number mat3 type.
vec3 const acme::ZEROS_VEC3
Zeros vec3 type.
mat3 const acme::ZEROS_MAT3
Zeros mat3 type.
vec3 const acme::ONES_VEC3
Ones vec3 type.
mat3 const acme::ONES_MAT3
Ones mat3 type.
mat3 const acme::IDENTITY_MAT3
Identity mat3 type.
vec4 const acme::UNITX_VEC4
X axis unit vec4 type.
vec4 const acme::UNITY_VEC4
Y axis unit vec4 type.
vec4 const acme::UNITZ_VEC4
Z axis unit vec4 type.
vec4 const acme::UNITW_VEC4
W axis unit vec4 type.
vec4 const acme::NAN_VEC4
Not-a-Number vec4 type.
mat4 const acme::NAN_MAT4
Not-a-Number mat4 type.
vec4 const acme::ZEROS_VEC4
Zeros vec4 type.
mat4 const acme::ZEROS_MAT4
Zeros mat4 type.
vec4 const acme::ONES_VEC4
Ones vec4 type.
mat4 const acme::ONES_MAT4
Ones mat4 type.
mat4 const acme::IDENTITY_MAT4
Identity mat4 type.
Referenced by acme::entity::rotate.
vec2 acme::THROWAWAY_VEC2
Throwaway vec2 type static non-const object.
vec3 acme::THROWAWAY_VEC3
Throwaway vec3 type static non-const object.
vec4 acme::THROWAWAY_VEC4
Throwaway vec4 type static non-const object.
mat2 acme::THROWAWAY_MAT2
Throwaway mat2 type static non-const object.
mat3 acme::THROWAWAY_MAT3
Throwaway mat3 type static non-const object.
mat4 acme::THROWAWAY_MAT4
Throwaway mat4 type static non-const object.
aabb const acme::NAN_AABB
Not-a-Number static const aabb object.
aabb acme::THROWAWAY_AABB
Throwaway static non-const aabb object.
ball const acme::NAN_BALL
Not-a-Number static const ball object.
ball acme::THROWAWAY_BALL
Throwaway static non-const ball object.
disk const acme::NAN_DISK
Not-a-Number static const disk object.
disk acme::THROWAWAY_DISK
Throwaway static non-const disk object.
line const acme::NAN_LINE
Not-a-Number static const line object.
line acme::THROWAWAY_LINE
Throwaway static non-const line object.
none acme::THROWAWAY_NONE
Throwaway static non-const none object.
plane const acme::NAN_PLANE
Not-a-Number static const plane object.
plane acme::plane_goat
Throwaway static non-const plane object.
point const acme::NAN_POINT
Not-a-Number static const point object.
Referenced by acme::aabb::clear.
point acme::THROWAWAY_POINT
Throwaway static non-const point object.
ray const acme::NAN_RAY
Not-a-Number static const ray object.
ray acme::THROWAWAY_RAY
Throwaway static non-const ray object.
segment const acme::NAN_SEGMENT
Not-a-Number static const segment object.
segment acme::THROWAWAY_SEGMENT
Throwaway static non-const segment object.
triangle const acme::NAN_TRIANGLE
Not-a-Number static const triangle object.
triangle acme::THROWAWAY_TRIANGLE
Throwaway static non-const triangle object.
bool acme::isCollinear(entity const *entity0_in, entity const *entity1_in, real tolerance=EPSILON)
Input entity 0
Referenced by intersection.
bool acme::isCollinear(line const &line0_in, line const &line1_in, real tolerance=EPSILON)
Input line 0
bool acme::isCollinear(ray const &ray0_in, ray const &ray1_in, real tolerance=EPSILON)
Input ray 0
bool acme::isCollinear(segment const &segment0_in, segment const &segment1_in, real tolerance=EPSILON)
Input segment 0
bool acme::isCollinear(line const &line_in, ray const &ray_in, real tolerance=EPSILON)
Input line
bool acme::isCollinear(line const &line_in, segment const &segment_in, real tolerance=EPSILON)
Input line
bool acme::isCollinear(ray const &ray_in, segment const &segment_in, real tolerance=EPSILON)
Input ray
bool acme::isCoplanar(entity const *entity0_in, entity const *entity1_in, real tolerance=EPSILON)
Input entity 0
Referenced by intersection, isCoplanar.
bool acme::isCoplanar(line const &line0_in, line const &line1_in, real tolerance=EPSILON)
Input line 0
bool acme::isCoplanar(ray const &ray0_in, ray const &ray1_in, real tolerance=EPSILON)
Input ray 0
bool acme::isCoplanar(plane const &plane0_in, plane const &plane1_in, real tolerance=EPSILON)
Input plane 0
bool acme::isCoplanar(segment const &segment0_in, segment const &segment1_in, real tolerance=EPSILON)
Input segment 0
bool acme::isCoplanar(triangle const &triangle0_in, triangle const &triangle1_in, real tolerance=EPSILON)
Input triangle 0
bool acme::isCoplanar(disk const &disk0_in, disk const &disk1_in, real tolerance=EPSILON)
Input disk 0
bool acme::isCoplanar(line const &line_in, ray const &ray_in, real tolerance=EPSILON)
Input line
bool acme::isCoplanar(line const &line_in, plane const &plane_in, real tolerance=EPSILON)
Input line
bool acme::isCoplanar(line const &line_in, segment const &segment_in, real tolerance=EPSILON)
Input line
bool acme::isCoplanar(line const &line_in, triangle const &triangle_in, real tolerance=EPSILON)
Input line
bool acme::isCoplanar(line const &line_in, disk const &disk_in, real tolerance=EPSILON)
Input line
bool acme::isCoplanar(ray const &ray_in, plane const &plane_in, real tolerance=EPSILON)
Input ray
bool acme::isCoplanar(ray const &ray_in, segment const &segment_in, real tolerance=EPSILON)
Input ray
bool acme::isCoplanar(ray const &ray_in, triangle const &triangle_in, real tolerance=EPSILON)
Input ray
bool acme::isCoplanar(ray const &ray_in, disk const &disk_in, real tolerance=EPSILON)
Input ray
bool acme::isCoplanar(plane const &plane_in, segment const &segment_in, real tolerance=EPSILON)
Input plane
bool acme::isCoplanar(plane const &plane_in, triangle const &triangle_in, real tolerance=EPSILON)
Input plane
bool acme::isCoplanar(plane const &plane_in, disk const &disk_in, real tolerance=EPSILON)
Input plane
bool acme::isCoplanar(segment const &segment_in, triangle const &triangle_in, real tolerance=EPSILON)
Input segment
bool acme::isCoplanar(segment const &segment_in, disk const &disk_in, real tolerance=EPSILON)
Input segment
bool acme::isCoplanar(triangle const &triangle_in, disk const &disk_in, real tolerance=EPSILON)
Input triangle
entity * acme::intersection(entity const *entity0_in, entity const *entity1_in, real tolerance=EPSILON)
Input entity 0
Referenced by acme::collection::intersection, intersection.
bool acme::intersection(point const &point0_in, point const &point1_in, point &point_out=THROWAWAY_POINT, real tolerance=EPSILON)
Input point 0
bool acme::intersection(point const &point_in, line const &line_in, point &point_out=THROWAWAY_POINT, real tolerance=EPSILON)
Input point
bool acme::intersection(point const &point_in, ray const &ray_in, point &point_out=THROWAWAY_POINT, real tolerance=EPSILON)
Input point
bool acme::intersection(point const &point_in, plane const &plane_in, point &point_out=THROWAWAY_POINT, real tolerance=EPSILON)
Input point
bool acme::intersection(point const &point_in, segment const &segment_in, point &point_out=THROWAWAY_POINT, real tolerance=EPSILON)
Input point
bool acme::intersection(point const &point_in, triangle const &triangle_in, point &point_out=THROWAWAY_POINT, real tolerance=EPSILON)
Input point
bool acme::intersection(point const &point_in, disk const &disk_in, point &point_out=THROWAWAY_POINT, real tolerance=EPSILON)
Input point
bool acme::intersection(line const &line0_in, line const &line1_in, line &line_out=THROWAWAY_LINE, real tolerance=EPSILON)
Input line 0
Intersection between two lines WARNING: This function only support collinear objects!
bool acme::intersection(ray const &ray0_in, ray const &ray1_in, ray &ray_out=THROWAWAY_RAY, real tolerance=EPSILON)
Input ray 0
Intersection between two rays WARNING: This function only support collinear objects!
bool acme::intersection(ray const &ray0_in, ray const &ray1_in, segment &segment_out=THROWAWAY_SEGMENT, real tolerance=EPSILON)
Input ray 0
Intersection between two opposite rays WARNING: This function only support collinear objects!
bool acme::intersection(segment const &segment0_in, segment const &segment1_in, segment &segment_out=THROWAWAY_SEGMENT, real tolerance=EPSILON)
Input segment 0
Intersection between two segments WARNING: This function only support collinear objects!
bool acme::intersection(line const &line_in, ray const &ray_in, ray &ray_out=THROWAWAY_RAY, real tolerance=EPSILON)
Input line
Intersection between line and ray WARNING: This function only support collinear objects!
bool acme::intersection(line const &line_in, segment const &segment_in, segment &segment_out=THROWAWAY_SEGMENT, real tolerance=EPSILON)
Input line
Intersection between line and segment WARNING: This function only support collinear objects!
bool acme::intersection(ray const &ray_in, segment const &segment_in, segment &segment_out=THROWAWAY_SEGMENT, real tolerance=EPSILON)
Input ray
Intersection between ray and segment WARNING: This function only support collinear objects!
bool acme::intersection(line const &line0_in, line const &line1_in, point &point_out=THROWAWAY_POINT, real tolerance=EPSILON)
Input line 0
Intersection between two lines WARNING: This function does not support collinear objects!
bool acme::intersection(ray const &ray0_in, ray const &ray1_in, point &point_out=THROWAWAY_POINT, real tolerance=EPSILON)
Input ray 0
Intersection between two rays WARNING: This function does not support collinear objects!
bool acme::intersection(segment const &segment0_in, segment const &segment1_in, point &point_out=THROWAWAY_POINT, real tolerance=EPSILON)
Input segment 0
Intersection between two segments WARNING: This function does not support collinear objects!
bool acme::intersection(line const &line_in, ray const &ray_in, point &point_out=THROWAWAY_POINT, real tolerance=EPSILON)
Input line
Intersection line with ray WARNING: This function does not support collinear objects!
bool acme::intersection(line const &line_in, segment const &segment, point &point_out=THROWAWAY_POINT, real tolerance=EPSILON)
Input line
Intersection line with segment WARNING: This function does not support collinear objects!
bool acme::intersection(ray const &ray_in, segment const &segment, point &point_out=THROWAWAY_POINT, real tolerance=EPSILON)
Input ray
Intersection ray with segment WARNING: This function does not support collinear objects!
bool acme::intersection(plane const &plane0_in, plane const &plane1_in, plane &plane_out=plane_goat, real tolerance=EPSILON)
Input plane 0
Intersection between planes WARNING: This function does only support coplanar objects!
bool acme::intersection(triangle const &triangle0_in, triangle const &triangle1_in, none &none_out=THROWAWAY_NONE, real tolerance=EPSILON)
Input triangle
Intersection triangle with disk WARNING: This function not supported!
bool acme::intersection(disk const &disk0_in, disk const &disk1_in, none &none_out=THROWAWAY_NONE, real tolerance=EPSILON)
Input disk
Intersection triangle with disk WARNING: This function not supported!
bool acme::intersection(line const &line_in, plane const &plane_in, line &line_out=THROWAWAY_LINE, real tolerance=EPSILON)
Input line
Intersection line with plane WARNING: This function does only support coplanar objects!
bool acme::intersection(line const &line_in, triangle const &triangle_in, segment &segment_out=THROWAWAY_SEGMENT, real tolerance=EPSILON)
Input line
Intersection line with triangle WARNING: This function does only support coplanar objects!
bool acme::intersection(line const &line_in, disk const &disk_in, segment &segment_out=THROWAWAY_SEGMENT, real tolerance=EPSILON)
Input line
Intersection line with disk WARNING: This function does only support coplanar objects!
bool acme::intersection(ray const &ray_in, plane const &plane_in, ray &ray_out=THROWAWAY_RAY, real tolerance=EPSILON)
Input ray
Intersection ray with plane WARNING: This function does only support coplanar objects!
bool acme::intersection(ray const &ray_in, triangle const &triangle_in, segment &segment_out=THROWAWAY_SEGMENT, real tolerance=EPSILON)
Input ray
Intersection ray with triangle WARNING: This function does only support coplanar objects!
bool acme::intersection(ray const &ray_in, disk const &disk_in, segment &segment_out=THROWAWAY_SEGMENT, real tolerance=EPSILON)
Input ray
Intersection ray with disk WARNING: This function does only support coplanar objects!
bool acme::intersection(plane const &plane_in, segment const &segment_in, segment &segment_out=THROWAWAY_SEGMENT, real tolerance=EPSILON)
Input plane
Intersection ray with plane WARNING: This function does only support coplanar objects!
bool acme::intersection(plane const &plane_in, triangle const &triangle_in, triangle &triangle_out=THROWAWAY_TRIANGLE, real tolerance=EPSILON)
Input plane
Intersection plane with triangle WARNING: This function does only support coplanar objects!
bool acme::intersection(plane const &plane_in, disk const &disk_in, disk &disk_out=THROWAWAY_DISK, real tolerance=EPSILON)
Input plane
Intersection plane with disk WARNING: This function does only support coplanar objects!
bool acme::intersection(segment const &segment_in, triangle const &triangle_in, segment &segment_out=THROWAWAY_SEGMENT, real tolerance=EPSILON)
Input segment
Intersection segment with triangle WARNING: This function does only support coplanar objects!
bool acme::intersection(segment const &segment_in, disk const &disk_in, segment &segment_out=THROWAWAY_SEGMENT, real tolerance=EPSILON)
Input segment
Intersection segment with disk WARNING: This function does only support coplanar objects!
bool acme::intersection(triangle const &triangle_in, disk const &disk_in, none &none_out=THROWAWAY_NONE, real tolerance=EPSILON)
Input triangle
Intersection triangle with disk WARNING: This function not supported!
bool acme::intersection(plane const &plane0_in, plane const &plane1_in, line &line_out=THROWAWAY_LINE, real tolerance=EPSILON)
Input plane 0
Intersection between two planes WARNING: This function does not support coplanarity!
bool acme::intersection(plane const &plane0_in, plane const &plane1_in, plane const &plane2_in, point &point_out=THROWAWAY_POINT, real tolerance=EPSILON)
Input plane 0
Intersection between three planes WARNING: This function does not support coplanarity!
bool acme::intersection(triangle const &triangle0_in, triangle const &triangle1_in, segment &segment_out=THROWAWAY_SEGMENT, real tolerance=EPSILON)
Input triangle 0
Intersection between triangles WARNING: This function does not support coplanarity!
bool acme::intersection(disk const &disk0_in, disk const &disk1_in, segment &segment_out=THROWAWAY_SEGMENT, real tolerance=EPSILON)
Input disk 0
Intersection between disks WARNING: This function does not support coplanarity!
bool acme::intersection(ball const &ball0_in, ball const &ball1_in, none &none_out=THROWAWAY_NONE, real tolerance=EPSILON)
Input ball 0
Intersection between balls WARNING: This function not supported!
bool acme::intersection(line const &line_in, plane const &plane_in, point &point_out=THROWAWAY_POINT, real tolerance=EPSILON)
Input line
Intersection line with plane WARNING: This function does not support coplanarity!
bool acme::intersection(line const &line_in, triangle const &triangle_in, point &point_out=THROWAWAY_POINT, real tolerance=EPSILON)
Input line
Intersection line with triangle WARNING: This function does not support coplanarity!
bool acme::intersection(line const &line_in, disk const &disk_in, point &point_out=THROWAWAY_POINT, real tolerance=EPSILON)
Input line
Intersection line and disk WARNING: This function does not support coplanarity!
bool acme::intersection(line const &line_in, ball const &ball_in, segment &segment_out=THROWAWAY_SEGMENT, real tolerance=EPSILON)
Input line
Intersection line and ball WARNING: This function does not support coplanarity!
bool acme::intersection(ray const &ray_in, plane const &plane_in, point &point_out=THROWAWAY_POINT, real tolerance=EPSILON)
Input ray
Intersection ray with plane WARNING: This function does not support coplanarity!
bool acme::intersection(ray const &ray_in, triangle const &triangle_in, point &point_out=THROWAWAY_POINT, real tolerance=EPSILON)
Input ray
Intersection ray with triangle WARNING: This function does not support coplanarity!
bool acme::intersection(ray const &ray_in, disk const &disk_in, point &point_out=THROWAWAY_POINT, real tolerance=EPSILON)
Input ray
Intersection ray with disk WARNING: This function does not support coplanarity!
bool acme::intersection(ray const &ray_in, ball const &ball_in, segment &segment_out=THROWAWAY_SEGMENT, real tolerance=EPSILON)
Input ray
Intersection ray and ball WARNING: This function does not support coplanarity!
bool acme::intersection(plane const &plane_in, segment const &segment, point &point_out=THROWAWAY_POINT, real tolerance=EPSILON)
Input plane
Intersection plane with segment WARNING: This function does not support coplanarity!
bool acme::intersection(plane const &plane_in, triangle const &triangle_in, segment &segment_out=THROWAWAY_SEGMENT, real tolerance=EPSILON)
Input plane
Intersection plane with triangle WARNING: This function does not support coplanarity!
bool acme::intersection(plane const &plane_in, disk const &disk_in, segment &segment_out=THROWAWAY_SEGMENT, real tolerance=EPSILON)
Input plane
Intersection plane with disk WARNING: This function does not support coplanarity!
bool acme::intersection(plane const &plane_in, ball const &ball_in, disk &disk_out=THROWAWAY_DISK, real tolerance=EPSILON)
Input plane
Intersection plane and ball WARNING: This function does not support coplanarity!
bool acme::intersection(segment const &segment_in, triangle const &triangle_in, point &point_out=THROWAWAY_POINT, real tolerance=EPSILON)
Input segment
Intersection ray with triangle WARNING: This function does not support coplanarity!
bool acme::intersection(segment const &segment_in, disk const &disk_in, point &point_out=THROWAWAY_POINT, real tolerance=EPSILON)
Input segment
Intersection segment with disk WARNING: This function does not support coplanarity!
bool acme::intersection(segment const &segment_in, ball const &ball_in, segment &segment_out=THROWAWAY_SEGMENT, real tolerance=EPSILON)
Input segment
Intersection segment and ball WARNING: This function does not support coplanarity!
bool acme::intersection(triangle const &triangle_in, disk const &disk_in, segment &segment_out=THROWAWAY_SEGMENT, real tolerance=EPSILON)
Input triangle
Intersection triangle with disk WARNING: This function does not support coplanarity!
bool acme::intersection(triangle const &triangle_in, ball const &ball_in, none &none_out=THROWAWAY_NONE, real tolerance=EPSILON)
Input triangle
Intersection triangle and ball WARNING: Function not supported!
bool acme::intersection(disk const &disk_in, ball const &ball_in, none &none_out=THROWAWAY_NONE, real tolerance=EPSILON)
Input disk
Intersection disk and ball WARNING: Function not supported!
bool acme::intersection(aabb const &aabb0_in, aabb const &aabb1_in, aabb &aabb_out=THROWAWAY_AABB, real tolerance=EPSILON)
Input aabb 0
bool acme::isApprox(real value0_in, real value1_in, real tolerance=EPSILON)
Input value 0
Referenced by intersection, acme::ball::isApprox, acme::disk::isApprox, isCoplanar, acme::ball::isDegenerated, acme::disk::isDegenerated, acme::line::isDegenerated, acme::plane::isDegenerated, acme::ray::isDegenerated, acme::segment::isDegenerated, acme::triangle::isDegenerated, acme::line::isInside, acme::ray::isInside, isOrthogonal, isParallel.
void acme::transform(vec3 &vector, affine const &matrix)
Input vector to be transformed
Referenced by acme::line::transform, acme::plane::transform, acme::ray::transform.
real acme::angle(vec3 const vector0_in, vec3 const vector1_in)
Input vector 0
Referenced by acme::collection::rotate, acme::entity::rotate.
bool acme::isOrthogonal(entity const *entity0_in, entity const *entity1_in, real tolerance=EPSILON)
Input entity 0
Referenced by isOrthogonal, isParallel.
bool acme::isOrthogonal(vec3 const &vector0_in, vec3 const &vector1_in, real tolerance=EPSILON)
Input vector 0
bool acme::isOrthogonal(vec3 const &vector_in, line const &line_in, real tolerance=EPSILON)
Input ray
bool acme::isOrthogonal(vec3 const &vector_in, ray const &ray_in, real tolerance=EPSILON)
Input vector
bool acme::isOrthogonal(vec3 const &vector_in, plane const &plane_in, real tolerance=EPSILON)
Input vector
bool acme::isOrthogonal(vec3 const &vector_in, segment const &segment_in, real tolerance=EPSILON)
Input vector
bool acme::isOrthogonal(vec3 const &vector_in, triangle const &triangle_in, real tolerance=EPSILON)
Input vector
bool acme::isOrthogonal(vec3 const &vector_in, disk const &disk_in, real tolerance=EPSILON)
Input vector
bool acme::isOrthogonal(line const &line0_in, line const &line1_in, real tolerance=EPSILON)
Input line 0
bool acme::isOrthogonal(ray const &ray0_in, ray const &ray1_in, real tolerance=EPSILON)
Input ray 0
bool acme::isOrthogonal(plane const &plane0_in, plane const &plane1_in, real tolerance=EPSILON)
Input plane 0
bool acme::isOrthogonal(segment const &segment0_in, segment const &segment1_in, real tolerance=EPSILON)
Input segment 0
bool acme::isOrthogonal(triangle const &triangle0_in, triangle const &triangle1_in, real tolerance=EPSILON)
Input triangle 0
bool acme::isOrthogonal(disk const &disk0_in, disk const &disk1_in, real tolerance=EPSILON)
Input disk 0
bool acme::isOrthogonal(line const &line_in, ray const &ray_in, real tolerance=EPSILON)
Input line
bool acme::isOrthogonal(line const &line_in, plane const &plane_in, real tolerance=EPSILON)
Input line
bool acme::isOrthogonal(line const &line_in, segment const &segment_in, real tolerance=EPSILON)
Input line
bool acme::isOrthogonal(line const &line_in, triangle const &triangle_in, real tolerance=EPSILON)
Input line
bool acme::isOrthogonal(line const &line_in, disk const &disk_in, real tolerance=EPSILON)
Input line
bool acme::isOrthogonal(ray const &ray_in, plane const &plane_in, real tolerance=EPSILON)
Input ray
bool acme::isOrthogonal(ray const &ray_in, segment const &segment_in, real tolerance=EPSILON)
Input ray
bool acme::isOrthogonal(ray const &ray_in, triangle const &triangle_in, real tolerance=EPSILON)
Input ray
bool acme::isOrthogonal(ray const &ray_in, disk const &disk_in, real tolerance=EPSILON)
Input ray
bool acme::isOrthogonal(plane const &plane_in, segment const &segment_in, real tolerance=EPSILON)
Input plane
bool acme::isOrthogonal(plane const &plane_in, triangle const &triangle_in, real tolerance=EPSILON)
Input plane
bool acme::isOrthogonal(plane const &plane_in, disk const &disk_in, real tolerance=EPSILON)
Input plane
bool acme::isOrthogonal(segment const &segment_in, triangle const &triangle_in, real tolerance=EPSILON)
Input segment
bool acme::isOrthogonal(segment const &segment_in, disk const &disk_in, real tolerance=EPSILON)
Input segment
bool acme::isOrthogonal(triangle const &triangle_in, disk const &disk_in, real tolerance=EPSILON)
Input triangle
bool acme::isParallel(entity const *entity0_in, entity const *entity1_in, real tolerance=EPSILON)
Input entity 0
Referenced by intersection, isCollinear, isCoplanar, isOrthogonal, isParallel.
bool acme::isParallel(vec3 const &vector0_in, vec3 const &vector1_in, real tolerance=EPSILON)
Input vector 0
bool acme::isParallel(vec3 const &vector_in, line const &line_in, real tolerance=EPSILON)
Input ray
bool acme::isParallel(vec3 const &vector_in, ray const &ray_in, real tolerance=EPSILON)
Input vector
bool acme::isParallel(vec3 const &vector_in, plane const &plane_in, real tolerance=EPSILON)
Input vector
bool acme::isParallel(vec3 const &vector_in, segment const &segment_in, real tolerance=EPSILON)
Input vector
bool acme::isParallel(vec3 const &vector_in, triangle const &triangle_in, real tolerance=EPSILON)
Input vector
bool acme::isParallel(vec3 const &vector_in, disk const &disk_in, real tolerance=EPSILON)
Input vector
bool acme::isParallel(line const &line0_in, line const &line1_in, real tolerance=EPSILON)
Input line 0
bool acme::isParallel(ray const &ray0_in, ray const &ray1_in, real tolerance=EPSILON)
Input ray 0
bool acme::isParallel(plane const &plane0_in, plane const &plane1_in, real tolerance=EPSILON)
Input plane 0
bool acme::isParallel(segment const &segment0_in, segment const &segment1_in, real tolerance=EPSILON)
Input segment 0
bool acme::isParallel(triangle const &triangle0_in, triangle const &triangle1_in, real tolerance=EPSILON)
Input triangle 0
bool acme::isParallel(disk const &disk0_in, disk const &disk1_in, real tolerance=EPSILON)
Input disk 0
bool acme::isParallel(line const &line_in, ray const &ray_in, real tolerance=EPSILON)
Input line
bool acme::isParallel(line const &line_in, plane const &plane_in, real tolerance=EPSILON)
Input line
bool acme::isParallel(line const &line_in, segment const &segment_in, real tolerance=EPSILON)
Input line
bool acme::isParallel(line const &line_in, triangle const &triangle_in, real tolerance=EPSILON)
Input line
bool acme::isParallel(line const &line_in, disk const &disk_in, real tolerance=EPSILON)
Input line
bool acme::isParallel(ray const &ray_in, plane const &plane_in, real tolerance=EPSILON)
Input ray
bool acme::isParallel(ray const &ray_in, segment const &segment_in, real tolerance=EPSILON)
Input ray
bool acme::isParallel(ray const &ray_in, triangle const &triangle_in, real tolerance=EPSILON)
Input ray
bool acme::isParallel(ray const &ray_in, disk const &disk_in, real tolerance=EPSILON)
Input ray
bool acme::isParallel(plane const &plane_in, segment const &segment_in, real tolerance=EPSILON)
Input plane
bool acme::isParallel(plane const &plane_in, triangle const &triangle_in, real tolerance=EPSILON)
Input plane
bool acme::isParallel(plane const &plane_in, disk const &disk_in, real tolerance=EPSILON)
Input plane
bool acme::isParallel(segment const &segment_in, triangle const &triangle_in, real tolerance=EPSILON)
Input segmentz
bool acme::isParallel(segment const &segment_in, disk const &disk_in, real tolerance=EPSILON)
Input segment
bool acme::isParallel(triangle const &triangle_in, disk const &disk_in, real tolerance=EPSILON)
Input triangle
out_stream& acme::operator<<(out_stream &os, vec3 const &obj)
Output stream
out_stream& acme::operator<<(out_stream &os, point const &obj)
Output stream
out_stream& acme::operator<<(out_stream &os, line const &obj)
Output stream
out_stream& acme::operator<<(out_stream &os, ray const &obj)
Output stream
out_stream& acme::operator<<(out_stream &os, plane const &obj)
Output stream
out_stream& acme::operator<<(out_stream &os, segment const &obj)
Output stream
out_stream& acme::operator<<(out_stream &os, aabb const &obj)
Output stream
out_stream& acme::operator<<(out_stream &os, triangle const &obj)
Output stream
out_stream& acme::operator<<(out_stream &os, disk const &obj)
Output stream
out_stream& acme::operator<<(out_stream &os, ball const &obj)
Output stream
out_stream& acme::operator<<(out_stream &os, affine const &obj)
Output stream
real acme::angle(vec3 const &vector0_in, vec3 const &vector1_in)