acme::plane
point acme::plane::m_origin
Plane origin point.
Referenced by d, isApprox, operator=, origin, signedDistance, transform, translate.
vec3 acme::plane::m_normal
Plane normal vector.
Referenced by d, isApprox, isDegenerated, normal, normalize, operator=, reverse, signedDistance, transform, unitNormal.
acme::plane::~plane()
Plane class destructor.
acme::plane::plane()
Plane class constructor.
acme::plane::plane(plane const &)=default
Plane copy constructor.
acme::plane::plane(plane &&)=default
Plane move constructor.
acme::plane::plane(real origin_x, real origin_y, real origin_z, real normal_x, real normal_y, real normal_z)
Input x value of plane origin point
acme::plane::plane(point const &origin, vec3 const &normal)
Input plane origin point
plane & acme::plane::operator=(plane const &plane_in)
Input plane object
bool acme::plane::isApprox(plane const &plane_in, real tolerance=EPSILON) const
Input plane object
point const & acme::plane::origin(void) const
Return plane origin point const reference.
Referenced by acme::disk::center, acme::disk::clamp, acme::intersection, acme::disk::isApprox, acme::isCoplanar, acme::disk::isInside.
point & acme::plane::origin(void)
Return plane origin point reference.
vec3 const & acme::plane::normal(void) const
Return plane normal vector const reference.
Referenced by acme::intersection, acme::disk::isApprox, acme::isCoplanar, acme::isOrthogonal, acme::isParallel, acme::disk::normal.
vec3 & acme::plane::normal(void)
Return plane normal vector reference.
vec3 acme::plane::unitNormal(void) const
Return plane normal unit vector.
Referenced by acme::intersection.
void acme::plane::normalize(void)
Normalize plane normal vector.
Referenced by acme::disk::normalize.
real acme::plane::d(void) const
Return plane equation d value (ax + by + cz + d = 0)
Referenced by acme::intersection.
real acme::plane::distance(point const &point_in) const
Input
Referenced by squaredDistance.
real acme::plane::squaredDistance(point const &point_in) const
Input
real acme::plane::signedDistance(point const &point_in) const
Input
Referenced by distance, acme::isCoplanar, isInside, squaredDistance.
void acme::plane::reverse(void)
Reverse plane normal vector.
Referenced by acme::disk::reverse.
void acme::plane::translate(vec3 const &vector_in) override
Input translation vector
Referenced by acme::disk::translate.
void acme::plane::transform(affine const &affine_in) override
4x4 affine transformation matrix
Referenced by acme::disk::transform.
bool acme::plane::isInside(point const &point_in, real tolerance=EPSILON) const
Query point
Referenced by acme::intersection, acme::disk::isInside.
bool acme::plane::isDegenerated(real tolerance=EPSILON) const override
Tolerance
Referenced by acme::disk::isDegenerated.
integer acme::plane::level(void) const override
Return object hierarchical level.
std::string acme::plane::type(void) const override
Return object type as string.
bool acme::plane::isNone(void) const override
Check whether the object is no entity.
bool acme::plane::isPoint(void) const override
Check whether the object is a point.
bool acme::plane::isLine(void) const override
Check whether the object is a line.
bool acme::plane::isRay(void) const override
Check whether the object is a ray.
bool acme::plane::isPlane(void) const override
Check whether the object is a plane.
bool acme::plane::isSegment(void) const override
Check whether the object is a segment.
bool acme::plane::isTriangle(void) const override
Check whether the object is a triangle.
bool acme::plane::isDisk(void) const override
Check whether the object is a disk.
bool acme::plane::isBall(void) const override
Check whether the object is a ball.
bool acme::plane::isClampable(void) const override
Check whether in the plane is clampable.
Referenced by clamp.
bool acme::plane::isNonClampable(void) const override
Check whether in the plane is non-clampable.
bool acme::plane::clamp(vec3 &min, vec3 &max) const override
Input minimum point
bool acme::plane::clamp(real &min_x, real &min_y, real &min_z, real &max_x, real &max_y, real &max_z) const override
Input x value of minimum point
void acme::entity::rotate(real angle, vec3 const &axis)
Input angle [rad]
bool acme::entity::isEntity(void) const
Check whether the object is an entity.
typedef std::shared_ptr<entity> acme::entity::ptr
Shared pointer to entity object.
typedef std::vector<ptr> acme::entity::vecptr
Vector of pointers to entity objects.