acme::triangle
point acme::triangle::m_vertex[3][3]
Triangle vertices.
Referenced by area, barycentric, centroid, clamp, edge, isApprox, isDegenerated, normal, operator=, operator[], perimeter, swap, transform, translate, triangle, vertex.
acme::triangle::~triangle()
Triangle class destructor.
acme::triangle::triangle(triangle const &)=default
Triangle copy constructor.
acme::triangle::triangle(triangle &&)=default
Triangle move constructor.
acme::triangle::triangle()
Triangle class constructor.
acme::triangle::triangle(real vertex0_x, real vertex0_y, real vertex0_z, real vertex1_x, real vertex1_y, real vertex1_z, real vertex2_x, real vertex2_y, real vertex2_z)
Input x value of first triangle vertex
acme::triangle::triangle(point const &vertex0, point const &vertex1, point const &vertex2)
Input first triangle vertex point
acme::triangle::triangle(point const vertex[3])
Input triangle verices
triangle & acme::triangle::operator=(triangle const &triangle_in)
Input triangle object
bool acme::triangle::isApprox(triangle const &triangle_in, real tolerance=EPSILON) const
Input triangle object
point const & acme::triangle::vertex(size_t i) const
New triangle vertex
Referenced by acme::intersection.
point & acme::triangle::vertex(size_t i)
New triangle vertex
point const & acme::triangle::operator[](size_t i) const
New triangle vertex
point & acme::triangle::operator[](size_t i)
New triangle vertex
point acme::triangle::centroid(void) const
Get triangle centroid.
Referenced by layingPlane.
segment acme::triangle::edge(size_t i) const
Triangle i-th vertex index
Referenced by acme::intersection.
vec3 acme::triangle::normal(void) const
Get triangle face normal (normalized vector)
Referenced by acme::isOrthogonal, acme::isParallel, layingPlane.
void acme::triangle::swap(size_t i, size_t j)
Triangle i-th vertex index
real acme::triangle::perimeter(void) const
Calculate triangle perimeter length.
real acme::triangle::area(void) const
Calculate triangle area.
void acme::triangle::barycentric(point const &point_in, real &u, real &v, real &w) const
Input point
Referenced by isInside.
plane acme::triangle::layingPlane(void) const
Get triangle laying plane.
Referenced by acme::intersection, acme::isCoplanar.
void acme::triangle::translate(vec3 const &vector_in) override
Input translation vector
void acme::triangle::transform(affine const &affine_in) override
4x4 affine transformation matrix
bool acme::triangle::isInside(point const &point_in, real tolerance=EPSILON) const
Query point
Referenced by acme::intersection.
bool acme::triangle::isDegenerated(real tolerance=EPSILON) const override
Tolerance
integer acme::triangle::level(void) const override
Return object hierarchical level.
std::string acme::triangle::type(void) const override
Return object type as string.
bool acme::triangle::isNone(void) const override
Check whether the object is no entity.
bool acme::triangle::isPoint(void) const override
Check whether the object is a point.
bool acme::triangle::isLine(void) const override
Check whether the object is a line.
bool acme::triangle::isRay(void) const override
Check whether the object is a ray.
bool acme::triangle::isPlane(void) const override
Check whether the object is a plane.
bool acme::triangle::isSegment(void) const override
Check whether the object is a segment.
bool acme::triangle::isTriangle(void) const override
Check whether the object is a triangle.
bool acme::triangle::isDisk(void) const override
Check whether the object is a disk.
bool acme::triangle::isBall(void) const override
Check whether the object is a ball.
bool acme::triangle::isClampable(void) const override
Check whether in the triangle is clampable.
Referenced by clamp.
bool acme::triangle::isNonClampable(void) const override
Check whether in the triangle is non-clampable.
bool acme::triangle::clamp(vec3 &min, vec3 &max) const override
Input minimum point
bool acme::triangle::clamp(real &min_x, real &min_y, real &min_z, real &max_x, real &max_y, real &max_z) const override
Input x value of minimum point
void acme::entity::rotate(real angle, vec3 const &axis)
Input angle [rad]
bool acme::entity::isEntity(void) const
Check whether the object is an entity.
typedef std::shared_ptr<entity> acme::entity::ptr
Shared pointer to entity object.
typedef std::vector<ptr> acme::entity::vecptr
Vector of pointers to entity objects.