acme::entity
typedef std::shared_ptr<entity> acme::entity::ptr
Shared pointer to entity object.
typedef std::vector<ptr> acme::entity::vecptr
Vector of pointers to entity objects.
virtual acme::entity::~entity()
Entity class destructor.
acme::entity::entity()
Entity class destructor.
virtual void acme::entity::translate(vec3 const &input)=0
Input translation vector
virtual void acme::entity::transform(affine const &matrix)=0
4x4 affine transformation matrix
Referenced by rotate.
void acme::entity::rotate(real angle, vec3 const &axis)
Input angle [rad]
virtual bool acme::entity::isDegenerated(real tolerance=EPSILON) const =0
Tolerance
virtual integer acme::entity::level(void) const =0
Return object hierarchical level.
Referenced by acme::intersection, acme::isCollinear, acme::isCoplanar, acme::isOrthogonal, acme::isParallel.
virtual std::string acme::entity::type(void) const =0
Return object type as string.
bool acme::entity::isEntity(void) const
Check whether the object is an entity.
virtual bool acme::entity::isNone(void) const =0
Check whether the object is no entity.
virtual bool acme::entity::isPoint(void) const =0
Check whether the object is a point.
Referenced by acme::intersection.
virtual bool acme::entity::isLine(void) const =0
Check whether the object is a line.
virtual bool acme::entity::isRay(void) const =0
Check whether the object is a ray.
virtual bool acme::entity::isPlane(void) const =0
Check whether the object is a plane.
virtual bool acme::entity::isSegment(void) const =0
Check whether the object is a segment.
virtual bool acme::entity::isTriangle(void) const =0
Check whether the object is a triangle.
virtual bool acme::entity::isDisk(void) const =0
Check whether the object is a disk.
virtual bool acme::entity::isBall(void) const =0
Check whether the object is a ball.
virtual bool acme::entity::isClampable(void) const =0
Check whether in the entity is clampable.
virtual bool acme::entity::isNonClampable(void) const =0
Check whether in the entity is non clampable.
virtual bool acme::entity::clamp(vec3 &min, vec3 &max) const =0
Input minimum point
virtual bool acme::entity::clamp(real &min_x, real &min_y, real &min_z, real &max_x, real &max_y, real &max_z) const =0
Input x value of minimum point