acme::segment
point acme::segment::m_vertex[2][2]
Segment extrema points.
Referenced by centroid, clamp, isApprox, isDegenerated, isInside, length, operator=, operator[], segment, swap, toUnitVector, toVector, transform, translate, vertex.
acme::segment::~segment()
Segment class destructor.
acme::segment::segment(segment const &)=default
Segment copy constructor.
acme::segment::segment(segment &&)=default
Segment move constructor.
acme::segment::segment()
Segment class constructor.
acme::segment::segment(real vertex0_x, real vertex0_y, real vertex0_z, real vertex1_x, real vertex1_y, real vertex1_z)
Input x value of first segment vertex
acme::segment::segment(point const &vertex0, point const &vertex1)
Input first segment vertex
acme::segment::segment(point const vertex[2])
Input segment vertices
segment & acme::segment::operator=(segment const &segment_in)
Input segment object
bool acme::segment::isApprox(segment const &segment_in, real tolerance=EPSILON) const
Input segment object
point acme::segment::centroid(void) const
Get segment centroid.
point const & acme::segment::vertex(size_t i) const
Intput segment i-th vertex index
Referenced by acme::intersection, acme::isCollinear, acme::isCoplanar.
point & acme::segment::vertex(size_t i)
Intput segment i-th vertex index
point const & acme::segment::operator[](size_t i) const
Intput segment i-th vertex index
point & acme::segment::operator[](size_t i)
Intput segment i-th vertex index
vec3 acme::segment::toVector(void) const
Convert segment to vector.
Referenced by acme::intersection.
vec3 acme::segment::toUnitVector(void) const
Convert segment to normalized vector.
Referenced by acme::intersection, acme::isCollinear, acme::isCoplanar, acme::isOrthogonal, acme::isParallel.
void acme::segment::swap(void)
Swap segment points.
real acme::segment::length(void) const
Calculate segment length.
Referenced by isInside.
void acme::segment::translate(vec3 const &vector_in) override
Input translation vector
void acme::segment::transform(affine const &affine_in) override
4x4 affine transformation matrix
bool acme::segment::isInside(point const &point_in, real tolerance=EPSILON) const
Query point
Referenced by acme::intersection.
bool acme::segment::isDegenerated(real tolerance=EPSILON) const override
Tolerance
integer acme::segment::level(void) const override
Return object hierarchical level.
std::string acme::segment::type(void) const override
Return object type as string.
bool acme::segment::isNone(void) const override
Check whether the object is no entity.
bool acme::segment::isPoint(void) const override
Check whether the object is a point.
bool acme::segment::isLine(void) const override
Check whether the object is a line.
bool acme::segment::isRay(void) const override
Check whether the object is a ray.
bool acme::segment::isPlane(void) const override
Check whether the object is a plane.
bool acme::segment::isSegment(void) const override
Check whether the object is a segment.
bool acme::segment::isTriangle(void) const override
Check whether the object is a triangle.
bool acme::segment::isDisk(void) const override
Check whether the object is a disk.
bool acme::segment::isBall(void) const override
Check whether the object is a ball.
bool acme::segment::isClampable(void) const override
Check whether in the segment is clampable.
Referenced by clamp.
bool acme::segment::isNonClampable(void) const override
Check whether in the segment is non-clampable.
bool acme::segment::clamp(vec3 &min, vec3 &max) const override
Input minimum point
bool acme::segment::clamp(real &min_x, real &min_y, real &min_z, real &max_x, real &max_y, real &max_z) const override
Input x value of minimum point
void acme::entity::rotate(real angle, vec3 const &axis)
Input angle [rad]
bool acme::entity::isEntity(void) const
Check whether the object is an entity.
typedef std::shared_ptr<entity> acme::entity::ptr
Shared pointer to entity object.
typedef std::vector<ptr> acme::entity::vecptr
Vector of pointers to entity objects.