acme::line
point acme::line::m_origin
Origin point.
Referenced by isApprox, isInside, operator=, origin, transform, translate.
vec3 acme::line::m_direction
Direction vector.
Referenced by direction, isApprox, isDegenerated, isInside, normalize, operator=, reverse, toUnitVector, toVector, transform.
acme::line::~line()
Line class destructor.
acme::line::line()
Line class constructor.
acme::line::line(line const &)=default
Line copy constructor.
acme::line::line(line &&)=default
Line move constructor.
acme::line::line(real ox, real oy, real oz, real dx, real dy, real dz)
Input x value of line origin point
acme::line::line(point const &origin, vec3 const &direction)
Input line origin point
line & acme::line::operator=(line const &line_in)
Input line object
bool acme::line::isApprox(line const &line_in, real tolerance=EPSILON) const
Input line object
point const & acme::line::origin(void) const
Return line origin point const reference.
Referenced by acme::intersection, acme::isCollinear, acme::isCoplanar.
point & acme::line::origin(void)
Return line origin point reference.
vec3 const & acme::line::direction(void) const
Return line direction vector const reference.
Referenced by acme::intersection, acme::isCollinear, acme::isCoplanar, acme::isOrthogonal, acme::isParallel.
vec3 & acme::line::direction(void)
Return line direction vector reference.
void acme::line::normalize(void)
Normalize line direction vector.
vec3 acme::line::toVector(void) const
Convert line to vector.
vec3 acme::line::toUnitVector(void) const
Convert line to normalized vector.
Referenced by acme::intersection.
void acme::line::reverse(void)
Reverse line direction.
void acme::line::translate(vec3 const &vector_in) override
Input translation vector
void acme::line::transform(affine const &affine_in) override
4x4 affine transformation matrix
bool acme::line::isInside(point const &point_in, real tolerance=EPSILON) const
Query point
Referenced by acme::intersection.
bool acme::line::isDegenerated(real tolerance=EPSILON) const override
Tolerance
integer acme::line::level(void) const override
Return object hierarchical level.
std::string acme::line::type(void) const override
Return object type as string.
bool acme::line::isNone(void) const override
Check whether the object is no entity.
bool acme::line::isPoint(void) const override
Check whether the object is a point.
bool acme::line::isLine(void) const override
Check whether the object is a line.
bool acme::line::isRay(void) const override
Check whether the object is a ray.
bool acme::line::isPlane(void) const override
Check whether the object is a plane.
bool acme::line::isSegment(void) const override
Check whether the object is a segment.
bool acme::line::isTriangle(void) const override
Check whether the object is a triangle.
bool acme::line::isDisk(void) const override
Check whether the object is a disk.
bool acme::line::isBall(void) const override
Check whether the object is a ball.
bool acme::line::isClampable(void) const override
Check whether in the line is clampable.
Referenced by clamp.
bool acme::line::isNonClampable(void) const override
Check whether in the line is non-clampable.
bool acme::line::clamp(vec3 &min, vec3 &max) const override
Input minimum point
bool acme::line::clamp(real &min_x, real &min_y, real &min_z, real &max_x, real &max_y, real &max_z) const override
Input x value of minimum point
void acme::entity::rotate(real angle, vec3 const &axis)
Input angle [rad]
bool acme::entity::isEntity(void) const
Check whether the object is an entity.
typedef std::shared_ptr<entity> acme::entity::ptr
Shared pointer to entity object.
typedef std::vector<ptr> acme::entity::vecptr
Vector of pointers to entity objects.